#!/bin/sh /etc/rc.common
START=99

sdu_ip6()
{
    local enable
    config_get_bool enable $1 enable
    
    if [ $enable ]; then
        local ipv6gateway

        config_get ipv6gateway $1 ipv6gateway
        
        /usr/bin/sdu/set6gateway $ipv6gateway >/var/log/sdu6
    fi
}

start()
{
    config_load sdunet
    config_foreach sdu_ip6 login
}
