#!/bin/sh /etc/rc.common

sdu_ip6()
{
    local enable
    config_get_bool enable $1 enable
    
    if [ $enable ]; then
        local ipv6gateway

        config_get ipv6gateway $1 ipv6gateway

        route -A inet6 add default gw $ipv6gateway

        echo "IPv6 Gateway Set to "$ipv6gateway"."
    fi
}

run_it()
{
    config_load sdunet
    config_foreach sdu_ip6 login
}

test6()
{
    ping_code=`ping6 2001:da8::1 -c 3`
    ping_code=${ping_code##*received, }
    ping_code=${ping_code% packet*}

    if [ $ping_code=='0%' ]; then
        echo 'ok6'
    else
        echo 0
    fi
}

run_loop()
{
    testcode=$(test6)
    testcode=${testcode%6}

    if [ $testcode == 'ok' ]; then
        run_it
    else
        sleep 5
        echo 'Waiting for IPv6 connection.'
        run_loop
    fi
}

start()
{
    run_loop
}
